apiVersion: v1
kind: Pod
metadata:
  name: kafka-monitor
  labels:
    app: kafka-monitor
spec:
  containers:
    - name: kafka-monitor
      image: quay.io/samsung_cnct/kafka-monitor:0.1
      ports:
      - containerPort: 8000
        name: gui
      - containerPort: 8778
        name: metrics

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-monitor
  labels:
    app: kafka-monitor
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    name: gui
  - port: 8778
    name: metrics
  selector:
    app: kafka-monitor